### ISSUE TITLE
403 Forbidden: You don't have permission to access this resource

### ISSUE THREAD

**Issue by zilton7** [twisted1919/mailwizz-ruby-sdk#1]
Why some endpoints throw:

`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>403 Forbidden</title> </head><body> <h1>Forbidden</h1> <p>You don't have permission to access this resource.</p> </body></html> `

Even though I have no permissions set at all?

Endpoints I am talking about:
`unsubscribe` & `unsubscribe_by_email`

**Comment by twisted1919** [comment]
This seem to be coming from your web server.

**Comment by zilton7** [comment]
yes, thanks for your reply. It seems I was able to fix it following the last comment here https://forum.centos-webpanel.com/index.php?topic=9359.0
